#!/usr/bin/env perl

# Enable Modern Perl.
use feature ':5.36';

use constant DEBUG => 1;

# Pascal mode for keywords and modifiers.
use constant {
    MODE_FPC    => 1 << 0,                  # 0001
    MODE_DELPHI => 1 << 1,                  # 0010
    
};

use constant {
    MODE_RELAX  => MODE_FPC | MODE_DELPHI,  # 0011
};

# The lint rule switches.
use constant {
    RULE_LONG_LINE  => 1 << 0,  # 0001
    RULE_SNAKE_CASE => 1 << 1,  # 0010
};
my $RULES = RULE_LONG_LINE | RULE_SNAKE_CASE;


# TODO: Set Pascal mode.
our %KEYWORDS = pascal_keywords();
our %SYMBOLS = pascal_symbols();
our %COMPOUND_SYMBOLS = pascal_compound_symbols();

# The main CLI program.
for my $arg (@ARGV) {
    my $file_name = $arg;
    open(my $FH, '<', $file_name) or die "Unable to open $file_name";

    my $lexer = lexer_create;
    my $line_number = 1;

    while (my $line = <$FH>) {
        lexer_lex($lexer, $line, $line_number);

        $line_number++;
    }

    close $FH;

    while (lexer_has_next($lexer)) {
        my $t = lexer_next($lexer);
        say token_format($t);
    }
}
# End of the main CLI program.


sub pascal_keywords($mode = MODE_RELAX) {
    # Free Pascal 3.2.2
    my @turboPascalKeywords = ('absolute', 'and', 'array', 'asm', 'begin',
        'case', 'const', 'constructor', 'destructor', 'div', 'do', 'downto',
        'else', 'end', 'file', 'for', 'function', 'goto', 'if',
        'implementation', 'in', 'inherited', 'inline', 'interface', 'label',
        'mod', 'nil', 'not', 'object', 'of', 'operator', 'or', 'packed',
        'procedure', 'program', 'record', 'reintroduce', 'repeat', 'self',
        'set', 'shl', 'shr', 'string', 'then', 'to', 'type', 'unit', 'until',
        'uses', 'var', 'while', 'with', 'xor');
    # Free Pascal 3.2.2
    my @objectPascalKeywords = ('as', 'class', 'dispinterface', 'except',
        'exports', 'finalization', 'finally', 'initialization', 'inline',
        'is', 'library', 'on', 'out', 'packed', 'property', 'raise',
        'resourcestring', 'threadvar', 'try');
    # Delphi 13.1
    my @delphiKeywords = ('and', 'end', 'interface', 'record', 'var', 'array',
        'except', 'is', 'repeat', 'while', 'as', 'exports', 'label',
        'resourcestring', 'with', 'asm', 'file', 'library', 'set', 'xor',
        'begin', 'finalization', 'mod', 'shl', 'case', 'finally', 'nil',
        'shr', 'class', 'for', 'not', 'string', 'const', 'function', 'object',
        'then', 'constructor', 'goto', 'of', 'threadvar', 'destructor', 'if',
        'or', 'to', 'dispinterface', 'implementation', 'packed', 'try', 'div',
        'in', 'procedure', 'type', 'do', 'inherited', 'program', 'unit',
        'downto', 'initialization', 'property', 'until', 'else', 'inline',
        'raise', 'uses');

    my %ks = ();

    if ($mode & MODE_FPC) {
        for my $k (@turboPascalKeywords) {
            $ks{$k} = 1;  # True
        }

        for my $k (@objectPascalKeywords) {
            $ks{$k} = 1;  # True
        }
    }

    if ($mode & MODE_DELPHI) {
        for my $k (@delphiKeywords) {
            $ks{$k} = 1;  # True
        }
    }

    return %ks;
}

sub pascal_symbols($mode = MODE_RELAX) {
    # Free Pascal 3.2.2
    my @freePascalSymbols = (
        "'", '+', '-', '*',  '/', '=', '<', '>', '[', ']', '.', ',', '(', ')',
        ':', '^',  '@', '{', '}', '$', '#', '&', '%'
    );
    # Delphi 13.1
    my @delphiSymbols = (
        '#', '$', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';',
        '<', '=', '>', '@', '[', ']', '^', '{', '}'
    );

    my %ss = ();

    if ($mode & MODE_FPC) {
        for my $s (@freePascalSymbols) {
            $ss{$s} = 1;  # True
        }
    }

    if ($mode & MODE_DELPHI) {
        for my $s (@delphiSymbols) {
            $ss{$s} = 1;  # True
        }
    }

    return %ss;
}

sub pascal_compound_symbols($mode = MODE_RELAX) {
    # Free Pascal 3.2.2
    my @freePascalSymbols = (
        '<<', '>>', '**', '<>', '><', '<=', '>=', ':=', '+=', '-=', '*=', '/=',
        '(*', '*)', '(.', '.)', '//'
    );
    # Delphi 13.1
    my @delphiSymbols = (
        '(*', '(.', '*)', '.)', '..', '//', ':=', '<=', '>=', '<>'
    );

    my %ss = ();

    if ($mode & MODE_FPC) {
        for my $s (@freePascalSymbols) {
            $ss{$s} = 1;  # True
        }
    }

    if ($mode & MODE_DELPHI) {
        for my $s (@delphiSymbols) {
            $ss{$s} = 1;  # True
        }
    }

    return %ss;
}


use constant {
    TOKEN_TYPE    => 'type',
    TOKEN_CONTENT => 'content',
    TOKEN_LINE    => 'line',
    TOKEN_COLUMN  => 'column',
};

use constant {
    TOKEN_TYPE_UNKNOWN     => 'unknown',
    TOKEN_TYPE_SPACE       => 'space',
    TOKEN_TYPE_DECLARATION => 'declaration',
    TOKEN_TYPE_ASSIGNMENT  => 'assignment',
    TOKEN_TYPE_EQUALITY    => 'equality',
    TOKEN_TYPE_STATEMENT   => 'statement',
    TOKEN_TYPE_SYMBOL      => 'symbol',
    TOKEN_TYPE_KEYWORD     => 'keyword',
    TOKEN_TYPE_IDENTIFIER  => 'identifier',
    TOKEN_TYPE_NEWLINE     => 'newline',
    TOKEN_TYPE_CODE        => 'code',
};

use constant {
    LEXER_TOKENS => 'tokens',
    LEXER_INDEX  => 'index',
};


# The fuzzy lexer.
sub lexer_create() {
    my $lexer = {};
    $lexer->{LEXER_TOKENS} = ();
    $lexer->{LEXER_INDEX} = 0;
    return $lexer;
}

sub lexer_has_next($lexer) {
    my $index = $lexer->{LEXER_INDEX};
    my $len = scalar @{$lexer->{LEXER_TOKENS}};
    return $index < $len;
}

sub lexer_next($lexer) {
    my $i = $lexer->{LEXER_INDEX};
    my $t = @{$lexer->{LEXER_TOKENS}}[$i];
    ($lexer->{LEXER_INDEX})++;
    return $t;
}

sub lexer_peek($lexer) {
    my $i = $lexer->{LEXER_INDEX};
    my $t = @{$lexer->{LEXER_TOKENS}}[$i];
    return $t;
}

sub lexer_lex($lexer, $s, $l) {
    my $i = 0;
    my $len = length($s);

    while ($i < $len) {
        my $peek = substr($s, $i, 1);
        my $j = $i;

        if (is_space($peek)) {
            while ($j < $len && is_space(substr($s, $j, 1))) {
                $j++;
            }

            # Discard space(s).

            $i = $j;
        }
        elsif (is_declaration($peek)) {
            my $t = token_create();

            if (is_assignment(substr($s, $j, 2))) {
                $j = $j + 2;

                token_set_type($t, TOKEN_TYPE_ASSIGNMENT);
            }
            else {
                $j++;

                token_set_type($t, TOKEN_TYPE_DECLARATION);
            }

            token_set_content($t, substr($s, $i, $j - $i));

            token_set_line_number($t, $l);
            token_set_column_number($t, $i + 1);

            push @{$lexer->{LEXER_TOKENS}}, $t;

            $i = $j;
        }
        elsif (is_equality($peek)) {
            my $t = token_create();

            token_set_type($t, TOKEN_TYPE_EQUALITY);
            token_set_content($t, $peek);

            token_set_line_number($t, $l);
            token_set_column_number($t, $i + 1);

            $j++;

            push @{$lexer->{LEXER_TOKENS}}, $t;

            $i = $j;
        }
        elsif (is_statement($peek)) {
            my $t = token_create();

            token_set_type($t, TOKEN_TYPE_STATEMENT);
            token_set_content($t, $peek);

            token_set_line_number($t, $l);
            token_set_column_number($t, $i + 1);

            $j++;

            push @{$lexer->{LEXER_TOKENS}}, $t;

            $i = $j;
        }
        elsif (is_symbol($peek)) {
            my $t = token_create();

            my $sym;
            if (is_compound_symbol(substr($s, $j, 2))) {
                $sym = substr($s, $j, 2);

                $j = $j + 2;
            }
            else {
                $sym = $peek;

                $j++;
            }

            token_set_type($t, TOKEN_TYPE_SYMBOL);
            token_set_content($t, $sym);

            token_set_line_number($t, $l);
            token_set_column_number($t, $i + 1);

            push @{$lexer->{LEXER_TOKENS}}, $t;

            $i = $j;
        }
        elsif (is_idenfitier_prefix($peek)) {
            my $t = token_create();

            while ($j < $len && is_identifier(substr($s, $j, 1))) {
                $j++;
            }

            my $word = substr($s, $i, $j - $i);
            if (is_keyword($word)) {
                token_set_type($t, TOKEN_TYPE_KEYWORD);
            } else {
                token_set_type($t, TOKEN_TYPE_IDENTIFIER);
            }

            token_set_content($t, $word);

            token_set_line_number($t, $l);
            token_set_column_number($t, $i + 1);

            push @{$lexer->{LEXER_TOKENS}}, $t;

            $i = $j;
        }
        elsif (is_newline($peek)) {
            my $t = token_create();

            token_set_type($t, TOKEN_TYPE_NEWLINE);
            token_set_content($t, $peek);

            token_set_line_number($t, $l);
            token_set_column_number($t, $i + 1);

            $j++;

            push @{$lexer->{LEXER_TOKENS}}, $t;

            $i = $j;
        }
        elsif (is_code($peek)) {
            my $t = token_create();

            while ($j < $len && is_code(substr($s, $j, 1))) {
                $j++;
            }

            token_set_type($t, TOKEN_TYPE_CODE);
            token_set_content($t, substr($s, $i, $j - $i));

            token_set_line_number($t, $l);
            token_set_column_number($t, $i + 1);

            push @{$lexer->{LEXER_TOKENS}}, $t;

            $i = $j;
        }
        else {
            # Discard anything else.
            # There may be some edge here.

            # Print vebatim.
            print $peek if (DEBUG);

            $j++;

            $i = $j;
        }
    }
}
# End of the fuzzy lexer.


# The token object.
sub token_create() {
    my $t = {};
    token_set_type($t, TOKEN_TYPE_UNKNOWN);
    token_set_content($t, '');
    token_set_line_number($t, 1);
    token_set_column_number($t, 1);
    return $t;
}

sub token_type($token) {
    return $token->{TOKEN_TYPE};
}

sub token_set_type($token, $type) {
    $token->{TOKEN_TYPE} = $type;
}

sub token_content($token) {
    return $token->{TOKEN_CONTENT};
}

sub token_set_content($token, $content) {
    $token->{TOKEN_CONTENT} = $content;
}

sub token_line_number($token) {
    return $token->{TOKEN_LINE};
}

sub token_set_line_number($token, $n) {
    $token->{TOKEN_LINE} = $n;
}

sub token_column_number($token) {
    return $token->{TOKEN_COLUMN};
}

sub token_set_column_number($token, $n) {
    $token->{TOKEN_COLUMN} = $n;
}

sub token_format($t) {
    "[" . $t->{TOKEN_TYPE} . "] "
    . "(" . $t->{TOKEN_LINE} . "," . $t->{TOKEN_COLUMN} . ") "
    . "<" . $t->{TOKEN_CONTENT} . ">";
}
# End of the token object.


# Utility subroutines.
sub is_keyword($k) {
    return $KEYWORDS{lc($k)};
}

sub is_symbol($s) {
    return $SYMBOLS{$s};
}

sub is_compound_symbol($s) {
    return $COMPOUND_SYMBOLS{$s};
}

sub is_idenfitier_prefix($s) {
    $s =~ /[A-Za-z_]/;
}

sub is_identifier($s) {
    $s =~ /[A-Za-z0-9_]/;
}

sub is_snake_case($s) {
    $s =~ /_?[A-Za-z][A-Za-z0-9]*_[A-Za-z0-9]+/;
}

sub is_space($s) {
    $s =~ /[ \t]/;
}

sub is_declaration($s) {
    $s eq ':';
}

sub is_assignment($s) {
    $s eq ':=';
}

sub is_equality($s) {
    $s eq '=';
}

sub is_statement($s) {
    $s eq ';';
}

sub is_newline($s) {
    $s eq "\n";
}

sub is_code($s) {
    return ((not is_identifier($s)) and (not is_space($s))
        and (not is_newline($s)) and (not is_symbol($s))); 
}